# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18NRglHCQ-H8y_aczJ1IjkIXVOGzEwUau
"""

print("Hello Anas, Wellcome")

message = "Hello Anas, This is AI Cademy."
print(message)

message = "Hello Anas, This is AI Cademy. Your Roll number is: "
r_num = 26
print( message + str(r_num) )

message = "Hello Anas, This is AI Cademy."
n=5
for x in range(n):
  print (message)

name = "Anas"
institute = "AiCademy"
print(name+" "+institute)

score1 = int(input("Enter the score 1: "))
score2 = int(input("Enter the score 2: "))
totalString = print(score1 + score2)
messageString = print("Total score is %s ")
#print(messageString % totalString)

Name = print("Anas")
institute = print("AiCademy")


score1 = int(input("Enter the score 1: "))
score2 = int(input("Enter the score 2: "))
totalString = score1 + score2
messageString = "Total score is {} ".format(totalString)

print(messageString )

totalInt = score1 + score2  # No need to convert to int again
messageString = "Total score is {} ".format(totalInt)
print(messageString)

score1 = int(input("Enter the score 1: "))
score2 = int(input("Enter the score 2: "))
total = score1 + score2
messageString = "score1({}) + score2({}) = {} ".format(score1, score2, total)  # Corrected the string format
print(messageString )

