# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qZnxQ9osvd4YBenqPz2LlGZiq-TwHPse
"""

a = int(input("Enter the Divident: "))
b = int(input("Enter the Divisor: "))
c = a/b
print("Answer: "+ str(c))

try:
  a = int(input("Enter the Divident: "))
  b = int(input("Enter the Divisor: "))
  c = a/b
  print("Answer: "+ c)
except:
  print("Error!")

# Conditional Tests
a = 29

# ==
if a == 29:
    print(bool(a))
else:
    print(a)


# !=
if a != 29:
    print(bool(a))
else:
    print(a)


# >
if a > 29:
    print(bool(a))
else:
    print(a)


# >=
if a >= 29:
    print(bool(a))
else:
    print(a)


# <
if a < 29:
    print(bool(a))
else:
    print(a)


# <=
if a <= 29:
    print(bool(a))
else:
    print(a)

